name: "Build and release example PDF"

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Install required dependencies
      #   run: |
      #     sudo apt update -y
      #     sudo apt install -y texlive texlive-science texlive-plain-generic texlive-pictures texlive-metapost texlive-latex-recommended texlive-latex-base texlive-latex-extra texlive-lang-english texlive-extra-utils texlive-binaries texlive-base texlive-bibtex-extra latexmk biber texlive-fonts-extra
      
      - name: Build
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: 2025
          run: |
            latexmk -gg example
          
      - name: Fetch release by tag
        id: fetch-release
        uses: pdamianik/release-tag-to-upload-url-action@v1.0.1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          token: ${{ github.token }}
        continue-on-error: true
        
      - uses: dev-drprasad/delete-tag-and-release@v1.1
        name: Delete release if already existing
        with:
          delete_release: true 
          tag_name: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.fetch-release.outcome == 'success'
                    
      - name: Create release
        id: create-release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ github.ref }}
          release_name: "Prebuilt example PDF"
          body: |
            Example PDF, generated by github actions.
          prerelease: true
          draft: false
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload pdf book
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ./example.pdf
          asset_name: example.pdf
          asset_content_type: application/pdf